CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media (
  id INT AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  resource_type VARCHAR(50) DEFAULT 'image',
  alt VARCHAR(255),
  caption TEXT,
  folder VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS news (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  excerpt TEXT,
  excerpt_en TEXT NULL,
  content LONGTEXT,
  content_en LONGTEXT NULL,
  cover_media_id INT,
  gallery JSON,
  status VARCHAR(50) DEFAULT 'draft',
  published_at DATETIME,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (cover_media_id) REFERENCES media(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description LONGTEXT,
  description_en LONGTEXT NULL,
  start_date DATETIME,
  end_date DATETIME,
  location VARCHAR(255),
  location_en VARCHAR(255) NULL,
  category VARCHAR(100),
  category_en VARCHAR(100) NULL,
  cover_media_id INT,
  gallery JSON,
  status VARCHAR(50) DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (cover_media_id) REFERENCES media(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS page_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  page_slug VARCHAR(255) NOT NULL UNIQUE,
  hero_title VARCHAR(255) NOT NULL,
  hero_title_en VARCHAR(255) NULL,
  hero_subtitle VARCHAR(255),
  hero_subtitle_en VARCHAR(255) NULL,
  hero_image_url VARCHAR(255),
  intro_title VARCHAR(255),
  intro_title_en VARCHAR(255) NULL,
  intro_text TEXT,
  intro_text_en TEXT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS directory_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NULL,
  subtitle VARCHAR(255),
  subtitle_en VARCHAR(255) NULL,
  description TEXT,
  description_en TEXT NULL,
  contact_info TEXT,
  contact_info_en TEXT NULL,
  gallery JSON,
  stats JSON,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gallery_albums (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255),
  media_urls JSON,
  section_date DATE,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
